/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import Database.OperationDB;
import Model.*;
import java.awt.Color;
import java.awt.Font;
import java.awt.GraphicsEnvironment;
import java.awt.Point;
import java.awt.Rectangle;
import java.awt.event.KeyEvent;
import java.sql.*;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Diba15
 */
public class HalPelanggan extends javax.swing.JFrame {

    Warung war = new Warung();
    private static final OperationDB op = new OperationDB();
    DefaultTableModel df;
    JTextField nominalUang = new JTextField();
    private String namaPengguna = null;
    private int posX, posY, posSize = 0;

    /**
     * Creates new form HalPelanggan
     *
     * @param nama
     */
    public HalPelanggan(String nama) {
        this.setUndecorated(true);
        initComponents();
        setExtendedState(getExtendedState() | MAXIMIZED_BOTH);
        JOptionPane.showMessageDialog(rootPane, "Klik Barang Untuk Membeli!", "Pemberitahuan", JOptionPane.INFORMATION_MESSAGE);
        jLabel1.setText("Selamat Datang " + nama);
        tableBarang.getTableHeader().setFont(new Font("Open Sans Condensed", Font.BOLD, 12));
        tableBarang.getTableHeader().setOpaque(false);
        tableBarang.getTableHeader().setBackground(new Color(101, 157, 189));
        df = (DefaultTableModel) tableBarang.getModel();
        resetSearchButton.setVisible(false);
        namaPengguna = nama;
        sortTableBarang();
        //Draggable Func
        Point center = GraphicsEnvironment.getLocalGraphicsEnvironment().getCenterPoint();
        int windowWidth = getWidth();
        int windowHeight = getHeight();
        setBounds(center.x - windowWidth / 2, center.y - windowHeight / 2, windowWidth,
            windowHeight);
        displayBarang();
    }

    public final void displayBarang() {
        try {
            ResultSet rs = op.readData("SELECT * FROM barang");
            int i = 1;
            while (rs.next()) {
                String namaBarang = rs.getString("namaBarang");
                String jenisBarang = rs.getString("jenisBarang");
                String jenis = rs.getString("jenis");
                String idBarang = rs.getString("id_barang");
                String rasa = rs.getString("rasa");
                int hargaBarang = rs.getInt("Harga");
                int qty = rs.getInt("kuantitas");
                if (jenisBarang.equalsIgnoreCase("Etc")) {
                    war.addBarangLain(jenis, idBarang, namaBarang, jenisBarang, qty, hargaBarang);
                } else {
                    war.addMakanMinum(rasa, jenis, idBarang, namaBarang, jenisBarang, qty, hargaBarang);
                }
                df.addRow(new Object[]{i, namaBarang, jenisBarang, hargaBarang, qty});
                i++;
            }

        } catch (SQLException ex) {
            Logger.getLogger(HalPelanggan.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
        public final void sortTableBarang() {
        int click = 1;
        TableRowSorter<TableModel> sorter = new TableRowSorter<>(tableBarang.getModel());
        tableBarang.setRowSorter(sorter);
        ArrayList<RowSorter.SortKey> sortKeys = new ArrayList<>();

        int columnIndexToSort = 1;
        if (click % 2 == 0) {
            sortKeys.add(new RowSorter.SortKey(columnIndexToSort, SortOrder.ASCENDING));
        } else {
            sortKeys.add(new RowSorter.SortKey(columnIndexToSort, SortOrder.DESCENDING));
        }
        click++;

        sorter.setSortKeys(sortKeys);
        sorter.sort();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jumlahBeliField = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnPanelLB = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        btnPanelExit = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableBarang = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        fieldCariBarang = new javax.swing.JTextField();
        buttonCari = new javax.swing.JButton();
        resetSearchButton = new javax.swing.JButton();

        jumlahBeliField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jumlahBeliFieldKeyPressed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(101, 157, 189));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setFocusable(false);
        setFont(new java.awt.Font("Open Sans Condensed", 0, 10)); // NOI18N

        jPanel1.setBackground(new java.awt.Color(85, 122, 149));
        jPanel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel1MouseDragged(evt);
            }
        });
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel1MousePressed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Open Sans Condensed", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Selamat Datang");

        btnPanelLB.setBackground(new java.awt.Color(101, 157, 189));
        btnPanelLB.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPanelLB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPanelLBMouseClicked(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Open Sans Condensed", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Dashboard");

        javax.swing.GroupLayout btnPanelLBLayout = new javax.swing.GroupLayout(btnPanelLB);
        btnPanelLB.setLayout(btnPanelLBLayout);
        btnPanelLBLayout.setHorizontalGroup(
            btnPanelLBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnPanelLBLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        btnPanelLBLayout.setVerticalGroup(
            btnPanelLBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnPanelLBLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnPanelExit.setBackground(new java.awt.Color(255, 51, 51));
        btnPanelExit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPanelExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPanelExitMouseClicked(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Open Sans Condensed", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Keluar");

        javax.swing.GroupLayout btnPanelExitLayout = new javax.swing.GroupLayout(btnPanelExit);
        btnPanelExit.setLayout(btnPanelExitLayout);
        btnPanelExitLayout.setHorizontalGroup(
            btnPanelExitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnPanelExitLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        btnPanelExitLayout.setVerticalGroup(
            btnPanelExitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnPanelExitLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel6.setBackground(new java.awt.Color(85, 122, 149));
        jPanel6.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel6MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel6MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel6MouseExited(evt);
            }
        });

        jLabel20.setBackground(new java.awt.Color(255, 255, 255));
        jLabel20.setFont(new java.awt.Font("Open Sans Condensed Light", 1, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText("-");
        jLabel20.setToolTipText("");
        jLabel20.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel20MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel20MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel20MouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addComponent(jLabel20)
                .addGap(24, 24, 24))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel20)
        );

        jPanel7.setBackground(new java.awt.Color(85, 122, 149));
        jPanel7.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel7MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel7MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel7MouseExited(evt);
            }
        });

        jLabel21.setBackground(new java.awt.Color(255, 255, 255));
        jLabel21.setFont(new java.awt.Font("Open Sans Condensed", 1, 12)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setText("max");
        jLabel21.setToolTipText("");
        jLabel21.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel21MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel21MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel21MouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addComponent(jLabel21)
                .addGap(24, 24, 24))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(jLabel21)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnPanelLB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnPanelExit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jPanel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnPanelLB, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPanelExit, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jPanel2.setBackground(new java.awt.Color(101, 157, 189));

        tableBarang.setFont(new java.awt.Font("Open Sans Condensed", 0, 11)); // NOI18N
        tableBarang.setForeground(new java.awt.Color(0, 0, 0));
        tableBarang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No", "Nama", "Jenis", "Harga", "Tersedia"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableBarang.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tableBarang.setFocusable(false);
        tableBarang.setIntercellSpacing(new java.awt.Dimension(0, 0));
        tableBarang.setRowHeight(25);
        tableBarang.setSelectionBackground(new java.awt.Color(101, 157, 189));
        tableBarang.setShowVerticalLines(false);
        tableBarang.getTableHeader().setReorderingAllowed(false);
        tableBarang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableBarangMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tableBarangMouseEntered(evt);
            }
        });
        jScrollPane1.setViewportView(tableBarang);

        jLabel2.setFont(new java.awt.Font("Open Sans Condensed", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setLabelFor(fieldCariBarang);
        jLabel2.setText("Cari Barang: ");

        buttonCari.setText("Cari");
        buttonCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCariActionPerformed(evt);
            }
        });

        resetSearchButton.setText("Reset Pencarian");
        resetSearchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetSearchButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 696, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fieldCariBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonCari)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(resetSearchButton)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(30, 30, 30))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(fieldCariBarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonCari)
                    .addComponent(resetSearchButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 345, Short.MAX_VALUE)
                .addGap(13, 13, 13))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tableBarangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableBarangMouseClicked
        int tablePoint = tableBarang.rowAtPoint(evt.getPoint());
        String nama = tableBarang.getValueAt(tablePoint, 1).toString();
        String namaBarang = null,idBarang = null,jenisBarang = null,rasa = null,jenis = null;
        int harga = 0,qty = 0;
        ResultSet rs = op.readData("SELECT * FROM barang WHERE namaBarang = '"+nama+"'");
        try {
            while (rs.next()) {
                namaBarang = rs.getString("namaBarang");
                idBarang = rs.getString("id_barang");
                jenisBarang = rs.getString("jenisBarang");
                rasa = rs.getString("rasa");
                jenis = rs.getString("jenis");
                harga = rs.getInt("harga");
                qty = rs.getInt("kuantitas");
            }
            
            //Fill String pesan
            String pesan = "Nama Barang: "+namaBarang+"\n";
            if (jenisBarang.equalsIgnoreCase("Makanan")) {
                pesan += "Rasa: "+rasa+"\n";
                pesan += "Jenis Makanan: "+jenis+"\n";
            } else if (jenisBarang.equalsIgnoreCase("Minuman")) {
                pesan += "Rasa: "+rasa+"\n";
                pesan += "Jenis Minuman: "+jenis+"\n";
            } else {
                pesan += "Jenis Barang: "+jenis+"\n";
            }
            pesan += "Harga: "+harga;
            Object[] beliMessage = {
                pesan,
                "Beli Berapa Banyak: ", jumlahBeliField,
                "Masukkan Nominal Uang Anda: ", nominalUang
            };
            
            int beli = JOptionPane.showConfirmDialog(rootPane, beliMessage, "Beli Barang", JOptionPane.OK_CANCEL_OPTION);
            if (beli == JOptionPane.OK_OPTION) {
                int jumlah = Integer.parseInt(jumlahBeliField.getText());
                int jumlahHarga = harga * jumlah;
                int nominal = Integer.parseInt(nominalUang.getText());
                int kembalian = nominal - jumlahHarga;
                int finalQty = qty - jumlah;
                if (kembalian < 0) {
                    JOptionPane.showMessageDialog(rootPane, "Uang anda kurang!","Peringatan",JOptionPane.WARNING_MESSAGE);
                } else {
                    df.setValueAt(finalQty, tablePoint, 4);
                    op.CUDData("UPDATE barang SET kuantitas = " + finalQty + " WHERE id_barang = '" + idBarang + "'");
                    op.CUDData("INSERT INTO transaksi(nama,id_Barang,nominalUang,jumlahBeli,kembalian) VALUES ('" + namaPengguna + "','" + idBarang + "',"
                            + nominal + "," + jumlah + "," + kembalian + ")");
                    String akhirPembayaran = "Harap Segera Bayar kepada cashier!\nTagihan Anda: " + jumlahHarga;
                    if (kembalian >= 0) {
                        akhirPembayaran += "\nKembalian: " + kembalian;
                    }
                    JOptionPane.showMessageDialog(rootPane, akhirPembayaran);
                }
                jumlahBeliField.setText(null);
                nominalUang.setText(null);
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(rootPane, e, "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_tableBarangMouseClicked

    private void jumlahBeliFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jumlahBeliFieldKeyPressed
        String isi = jumlahBeliField.getText();
        int l = isi.length();
        if (evt.getKeyChar() >= '1' && evt.getKeyChar() <= '9') {
            if (l == 2) {
                jumlahBeliField.setEditable(false);
            } else {
                jumlahBeliField.setEditable(true);
            }
        } else if (evt.getKeyCode() == KeyEvent.VK_BACK_SPACE) {
            jumlahBeliField.setEditable(true);
        } else {
            jumlahBeliField.setEditable(false);
        }
    }//GEN-LAST:event_jumlahBeliFieldKeyPressed

    private void buttonCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCariActionPerformed
        String cariNama = fieldCariBarang.getText();
        if (cariNama == null) {
            JOptionPane.showMessageDialog(rootPane, "Masukkan nama Barang dengan benar!", "Peringatan", JOptionPane.WARNING_MESSAGE);
        } else {
            df.setRowCount(0);
            resetSearchButton.setVisible(true);
            try {
                ResultSet rs = op.readData("SELECT * FROM barang WHERE namaBarang = '" + cariNama + "'");
                if (rs.next()) {
                    String id = rs.getString("id_barang");
                    String namaBarang = rs.getString("namaBarang");
                    String jenisBarang = rs.getString("jenisBarang");
                    String rasa = rs.getString("rasa");
                    String jenis = rs.getString("jenis");
                    int harga = rs.getInt("harga");
                    int qty = rs.getInt("kuantitas");
                    df.addRow(new Object[]{1, namaBarang, jenisBarang, harga, qty});
                    fieldCariBarang.setText(null);
                }
            } catch (SQLException ex) {
                Logger.getLogger(HalPelanggan.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_buttonCariActionPerformed

    private void resetSearchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetSearchButtonActionPerformed
        df.setRowCount(0);
        war.resetList();
        resetSearchButton.setVisible(false);
        try {
            ResultSet rs = op.readData("SELECT * FROM barang");
            int i = 1;
            while (rs.next()) {
                String namaBarang = rs.getString("namaBarang");
                String jenisBarang = rs.getString("jenisBarang");
                String jenis = rs.getString("jenis");
                String idBarang = rs.getString("id_barang");
                String rasa = rs.getString("rasa");
                int hargaBarang = rs.getInt("Harga");
                int qty = rs.getInt("kuantitas");
                if (jenisBarang.equalsIgnoreCase("Etc")) {
                    war.addBarangLain(jenis, idBarang, namaBarang, jenisBarang, qty, hargaBarang);
                } else {
                    war.addMakanMinum(rasa, jenis, idBarang, namaBarang, jenisBarang, qty, hargaBarang);
                }
                df.addRow(new Object[]{i, namaBarang, jenisBarang, hargaBarang, qty});
                i++;
            }

        } catch (SQLException ex) {
            Logger.getLogger(HalPelanggan.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_resetSearchButtonActionPerformed

    private void tableBarangMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableBarangMouseEntered

    }//GEN-LAST:event_tableBarangMouseEntered

    private void btnPanelLBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPanelLBMouseClicked

    }//GEN-LAST:event_btnPanelLBMouseClicked

    private void btnPanelExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPanelExitMouseClicked
        this.dispose();
        new GettingStarted().setVisible(true);
    }//GEN-LAST:event_btnPanelExitMouseClicked

    private void jLabel20MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel20MouseClicked
        setState(ICONIFIED);
    }//GEN-LAST:event_jLabel20MouseClicked

    private void jLabel20MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel20MouseEntered
        jPanel6.setBackground(new Color(101,157,189));
    }//GEN-LAST:event_jLabel20MouseEntered

    private void jLabel20MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel20MouseExited
        jPanel6.setBackground(new Color(85,122,149));
    }//GEN-LAST:event_jLabel20MouseExited

    private void jPanel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel6MouseClicked
        setState(ICONIFIED);
    }//GEN-LAST:event_jPanel6MouseClicked

    private void jPanel6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel6MouseEntered
        jPanel6.setBackground(new Color(101,157,189));
    }//GEN-LAST:event_jPanel6MouseEntered

    private void jPanel6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel6MouseExited
        jPanel6.setBackground(new Color(85,122,149));
    }//GEN-LAST:event_jPanel6MouseExited

    private void jLabel21MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel21MouseClicked
        if (getExtendedState() == NORMAL) {
            setExtendedState(MAXIMIZED_BOTH);
            posSize = 0;
            jLabel21.setText("max");
        } else {
            setExtendedState(NORMAL);
            posSize = 1;
            jLabel21.setText("min");
        }
    }//GEN-LAST:event_jLabel21MouseClicked

    private void jLabel21MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel21MouseEntered
        jPanel7.setBackground(new Color(101,157,189));
    }//GEN-LAST:event_jLabel21MouseEntered

    private void jLabel21MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel21MouseExited
        jPanel7.setBackground(new Color(85,122,149));
    }//GEN-LAST:event_jLabel21MouseExited

    private void jPanel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel7MouseClicked
        if (getExtendedState() == NORMAL) {
            setExtendedState(MAXIMIZED_BOTH);
            posSize = 0;
            jLabel21.setText("max");
        } else {
            setExtendedState(NORMAL);
            posSize = 1;
            jLabel21.setText("min");
        }
    }//GEN-LAST:event_jPanel7MouseClicked

    private void jPanel7MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel7MouseEntered
        jPanel7.setBackground(new Color(101,157,189));
    }//GEN-LAST:event_jPanel7MouseEntered

    private void jPanel7MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel7MouseExited
        jPanel7.setBackground(new Color(85,122,149));
    }//GEN-LAST:event_jPanel7MouseExited

    private void jPanel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MousePressed
        posX = evt.getX();
        posY = evt.getY();
    }//GEN-LAST:event_jPanel1MousePressed

    private void jPanel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseDragged
        if (posSize == 1) {
            Rectangle rectangle = getBounds();
            setBounds(evt.getXOnScreen() - posX, evt.getYOnScreen() - posY, rectangle.width, rectangle.height);
        }
    }//GEN-LAST:event_jPanel1MouseDragged
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HalPelanggan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btnPanelExit;
    private javax.swing.JPanel btnPanelLB;
    private javax.swing.JButton buttonCari;
    private javax.swing.JTextField fieldCariBarang;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jumlahBeliField;
    private javax.swing.JButton resetSearchButton;
    private javax.swing.JTable tableBarang;
    // End of variables declaration//GEN-END:variables
}
